#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiDados
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="BDTRANSF")]
	public partial class DespesasDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public DespesasDataContext() : 
				base(global::ApiDados.Properties.Settings.Default.BDTRANSFConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DespesasDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tblDadosContabeisImovel20210526> tblDadosContabeisImovel20210526s
		{
			get
			{
				return this.GetTable<tblDadosContabeisImovel20210526>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblDadosContabeisImovel20210526")]
	public partial class tblDadosContabeisImovel20210526
	{
		
		private string _Contrato;
		
		private string _baseprovisao;
		
		private string _Status1;
		
		private string _Status2;
		
		private string _TipoImovel;
		
		private string _UF;
		
		private string _CIDADE;
		
		private System.Nullable<double> _VALOR_TOTAL_IPTU_2021;
		
		private System.Nullable<double> _VALOR_PGTO_01_2021;
		
		private System.Nullable<double> _VALOR_PGTO_02_2021;
		
		private System.Nullable<double> _VALOR_PGTO_03_2021;
		
		private System.Nullable<double> _VALOR_PGTO_04_2021;
		
		private System.Nullable<double> _TOTAL_PAGTO_IPTU_2021;
		
		private System.Nullable<double> _VALOR_TOTAL_DIVIDA;
		
		private System.Nullable<double> _VALOR_TOTAL_DIVIDA_2;
		
		private System.Nullable<double> _VALOR_TOTAL_TOTAL;
		
		private string _VALOR_PGTO_DEBITO_ATRASADO;
		
		private string _PREVISAO;
		
		private System.Nullable<double> _PERIODO_REFIS_INICIO;
		
		private string _PERIODO_REFIS_TERMINO;
		
		private System.Nullable<double> _VALOR_TAX_CONDOMINIAL_ESTIMATIVA;
		
		private System.Nullable<double> _VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL;
		
		private System.Nullable<double> _VALOR_ESTIMADO_ATUALIZADO;
		
		private System.Nullable<double> _VALOR_PGTO_DIVIDA;
		
		private System.Nullable<double> _VALOR_PGTO_OUT_2020;
		
		private System.Nullable<double> _VALOR_PGTO_NOV_2020;
		
		private System.Nullable<double> _VALOR_PGTO_DEZ_2020;
		
		private System.Nullable<double> _VALOR_PGTO_JAN_2021;
		
		private System.Nullable<double> _VALOR_PGTO_FEV_2021;
		
		private System.Nullable<double> _VALOR_PGTO_MAR_2021;
		
		private System.Nullable<double> _VALOR_PGTO_ABR_2021;
		
		public tblDadosContabeisImovel20210526()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contrato", DbType="NVarChar(255)")]
		public string Contrato
		{
			get
			{
				return this._Contrato;
			}
			set
			{
				if ((this._Contrato != value))
				{
					this._Contrato = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_baseprovisao", DbType="NVarChar(255)")]
		public string baseprovisao
		{
			get
			{
				return this._baseprovisao;
			}
			set
			{
				if ((this._baseprovisao != value))
				{
					this._baseprovisao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status1", DbType="NVarChar(255)")]
		public string Status1
		{
			get
			{
				return this._Status1;
			}
			set
			{
				if ((this._Status1 != value))
				{
					this._Status1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status2", DbType="NVarChar(255)")]
		public string Status2
		{
			get
			{
				return this._Status2;
			}
			set
			{
				if ((this._Status2 != value))
				{
					this._Status2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TipoImovel", DbType="NVarChar(255)")]
		public string TipoImovel
		{
			get
			{
				return this._TipoImovel;
			}
			set
			{
				if ((this._TipoImovel != value))
				{
					this._TipoImovel = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UF", DbType="NVarChar(255)")]
		public string UF
		{
			get
			{
				return this._UF;
			}
			set
			{
				if ((this._UF != value))
				{
					this._UF = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CIDADE", DbType="NVarChar(255)")]
		public string CIDADE
		{
			get
			{
				return this._CIDADE;
			}
			set
			{
				if ((this._CIDADE != value))
				{
					this._CIDADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_IPTU_2021", DbType="Float")]
		public System.Nullable<double> VALOR_TOTAL_IPTU_2021
		{
			get
			{
				return this._VALOR_TOTAL_IPTU_2021;
			}
			set
			{
				if ((this._VALOR_TOTAL_IPTU_2021 != value))
				{
					this._VALOR_TOTAL_IPTU_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_01_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_01_2021
		{
			get
			{
				return this._VALOR_PGTO_01_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_01_2021 != value))
				{
					this._VALOR_PGTO_01_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_02_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_02_2021
		{
			get
			{
				return this._VALOR_PGTO_02_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_02_2021 != value))
				{
					this._VALOR_PGTO_02_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_03_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_03_2021
		{
			get
			{
				return this._VALOR_PGTO_03_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_03_2021 != value))
				{
					this._VALOR_PGTO_03_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_04_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_04_2021
		{
			get
			{
				return this._VALOR_PGTO_04_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_04_2021 != value))
				{
					this._VALOR_PGTO_04_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_PAGTO_IPTU_2021", DbType="Float")]
		public System.Nullable<double> TOTAL_PAGTO_IPTU_2021
		{
			get
			{
				return this._TOTAL_PAGTO_IPTU_2021;
			}
			set
			{
				if ((this._TOTAL_PAGTO_IPTU_2021 != value))
				{
					this._TOTAL_PAGTO_IPTU_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_DIVIDA", DbType="Float")]
		public System.Nullable<double> VALOR_TOTAL_DIVIDA
		{
			get
			{
				return this._VALOR_TOTAL_DIVIDA;
			}
			set
			{
				if ((this._VALOR_TOTAL_DIVIDA != value))
				{
					this._VALOR_TOTAL_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_DIVIDA_2", DbType="Float")]
		public System.Nullable<double> VALOR_TOTAL_DIVIDA_2
		{
			get
			{
				return this._VALOR_TOTAL_DIVIDA_2;
			}
			set
			{
				if ((this._VALOR_TOTAL_DIVIDA_2 != value))
				{
					this._VALOR_TOTAL_DIVIDA_2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_TOTAL", DbType="Float")]
		public System.Nullable<double> VALOR_TOTAL_TOTAL
		{
			get
			{
				return this._VALOR_TOTAL_TOTAL;
			}
			set
			{
				if ((this._VALOR_TOTAL_TOTAL != value))
				{
					this._VALOR_TOTAL_TOTAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_DEBITO_ATRASADO", DbType="NVarChar(255)")]
		public string VALOR_PGTO_DEBITO_ATRASADO
		{
			get
			{
				return this._VALOR_PGTO_DEBITO_ATRASADO;
			}
			set
			{
				if ((this._VALOR_PGTO_DEBITO_ATRASADO != value))
				{
					this._VALOR_PGTO_DEBITO_ATRASADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PREVISAO", DbType="NVarChar(255)")]
		public string PREVISAO
		{
			get
			{
				return this._PREVISAO;
			}
			set
			{
				if ((this._PREVISAO != value))
				{
					this._PREVISAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIODO_REFIS_INICIO", DbType="Float")]
		public System.Nullable<double> PERIODO_REFIS_INICIO
		{
			get
			{
				return this._PERIODO_REFIS_INICIO;
			}
			set
			{
				if ((this._PERIODO_REFIS_INICIO != value))
				{
					this._PERIODO_REFIS_INICIO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PERIODO_REFIS_TERMINO", DbType="NVarChar(255)")]
		public string PERIODO_REFIS_TERMINO
		{
			get
			{
				return this._PERIODO_REFIS_TERMINO;
			}
			set
			{
				if ((this._PERIODO_REFIS_TERMINO != value))
				{
					this._PERIODO_REFIS_TERMINO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TAX_CONDOMINIAL_ESTIMATIVA", DbType="Float")]
		public System.Nullable<double> VALOR_TAX_CONDOMINIAL_ESTIMATIVA
		{
			get
			{
				return this._VALOR_TAX_CONDOMINIAL_ESTIMATIVA;
			}
			set
			{
				if ((this._VALOR_TAX_CONDOMINIAL_ESTIMATIVA != value))
				{
					this._VALOR_TAX_CONDOMINIAL_ESTIMATIVA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL", DbType="Float")]
		public System.Nullable<double> VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL
		{
			get
			{
				return this._VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL;
			}
			set
			{
				if ((this._VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL != value))
				{
					this._VALOR_TOTAL_DA_DIVIDA_CONDOMINIAL = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_ESTIMADO_ATUALIZADO", DbType="Float")]
		public System.Nullable<double> VALOR_ESTIMADO_ATUALIZADO
		{
			get
			{
				return this._VALOR_ESTIMADO_ATUALIZADO;
			}
			set
			{
				if ((this._VALOR_ESTIMADO_ATUALIZADO != value))
				{
					this._VALOR_ESTIMADO_ATUALIZADO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_DIVIDA", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_DIVIDA
		{
			get
			{
				return this._VALOR_PGTO_DIVIDA;
			}
			set
			{
				if ((this._VALOR_PGTO_DIVIDA != value))
				{
					this._VALOR_PGTO_DIVIDA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_OUT_2020", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_OUT_2020
		{
			get
			{
				return this._VALOR_PGTO_OUT_2020;
			}
			set
			{
				if ((this._VALOR_PGTO_OUT_2020 != value))
				{
					this._VALOR_PGTO_OUT_2020 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_NOV_2020", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_NOV_2020
		{
			get
			{
				return this._VALOR_PGTO_NOV_2020;
			}
			set
			{
				if ((this._VALOR_PGTO_NOV_2020 != value))
				{
					this._VALOR_PGTO_NOV_2020 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_DEZ_2020", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_DEZ_2020
		{
			get
			{
				return this._VALOR_PGTO_DEZ_2020;
			}
			set
			{
				if ((this._VALOR_PGTO_DEZ_2020 != value))
				{
					this._VALOR_PGTO_DEZ_2020 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_JAN_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_JAN_2021
		{
			get
			{
				return this._VALOR_PGTO_JAN_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_JAN_2021 != value))
				{
					this._VALOR_PGTO_JAN_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_FEV_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_FEV_2021
		{
			get
			{
				return this._VALOR_PGTO_FEV_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_FEV_2021 != value))
				{
					this._VALOR_PGTO_FEV_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_MAR_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_MAR_2021
		{
			get
			{
				return this._VALOR_PGTO_MAR_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_MAR_2021 != value))
				{
					this._VALOR_PGTO_MAR_2021 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VALOR_PGTO_ABR_2021", DbType="Float")]
		public System.Nullable<double> VALOR_PGTO_ABR_2021
		{
			get
			{
				return this._VALOR_PGTO_ABR_2021;
			}
			set
			{
				if ((this._VALOR_PGTO_ABR_2021 != value))
				{
					this._VALOR_PGTO_ABR_2021 = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
